### ISSUE TITLE
Add an API for constructing a RangeMap that drops overlapping ranges

### ISSUE THREAD

**Issue by luser** [jneem/range-map#1]
Thanks for writing this crate! I'm using it in several places in my [`minidump`](https://github.com/luser/rust-minidump) crate to store data keyed by address range from minidump files, like the list of shared libraries from the process. Unfortunately sometimes minidumps have unusual data in them, including overlapping memory address ranges for certain data. Because of this my code can trigger a panic while attempting to construct a `RangeMap`. I can certainly change my code to sanitize the input data more thoroughly, but it would also be nice if `RangeMap` had an API that could do this for me since it knows what its preconditions are.

**Comment by jneem** [comment]
Hey, sorry for the slow reply (I had my github notifications set up wrong).

Could you be a bit more specific about what sort of data you want to allow? Unless there's a bug, `RangeMap` already supports being constructed with overlapping ranges, but it fails if you have overlapping ranges that map to different values. That is, if you try to map the range [0, 2] to "foo" and the range [1, 3] to "bar" then it fails (because what should `range.get(1)` return?).

Having said that, I think it's totally reasonable that I should be returning an `Option` or `Result` instead of panicking...

**Comment by luser** [comment]
I agree that there's probably not a one-size-fits-all solution here, but I feel pretty strongly that library crates shouldn't panic on bad data like this. I wound up writing a little trait to drop data that overlaps existing ranges for my own code:
https://github.com/luser/rust-minidump/blob/26af5e89267d335f37c1c3a6c9dd165064f38b88/minidump-common/src/traits.rs#L66-L103

Using it looks like this:
https://github.com/luser/rust-minidump/blob/26af5e89267d335f37c1c3a6c9dd165064f38b88/src/minidump.rs#L671-L672

I don't want to overengineer your crate's API for you, but at the very least making the creation methods return `Result<RangeMap<K, V>, Error>` would let callers handle this more gracefully. Ideally there'd also be some way to control the handling of overlapping ranges, like in case of overlap: a) keep the first range encountered, b) keep the last range encountered, c) keep the larger of the two ranges, etc.

**Comment by jneem** [comment]
I've just pushed (but not released on crates.io yet) a new version with the function `RangeMap::try_from_iter`. What do you think? It doesn't have configurable behavior (mostly because I couldn't think of a nice API for it), but instead it returns the ranges that were discarded and so the user can decide what to do with them.
